[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "2.2.6"

[[constraint]]
  name = "github.com/coreos/prometheus-operator"
  version = "0.29.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
